version: '3.8'

services:
    zookeeper:
      container_name: zookeeper
      build:
        context: ./zookeeper
        dockerfile: Dockerfile
      ports:
        - "2182:2182"

    kafka:
      container_name: kafka
      build:
        context: ./kafka
        dockerfile: Dockerfile
      ports:
        - "9092:9092"
      depends_on:
        - zookeeper

    middleware:
      container_name: middleware
      build:
        context: ./middleware
        dockerfile: Dockerfile
      ports:
        - "9090:9090"
      depends_on:
        - kafka
        